export enum EIcon {
  User = 'fa-user',
  MagnifyGlass = 'fa-magnifying-glass',
  ConfirmationSucess = 'fa-circle-check',
  ConfirmationCancel = 'fa-circle-xmark',
  ConfirmationWarning = 'fa-circle-exclamation',
  ConfirmationInfo = 'fa-circle-info',
  Role = 'fa-id-badge',
  Resource = 'fa-building-shield',
  Credential = 'fa-key',
  //Widgets
  WidgetBool = 'fa-toggle-off',
  WidgetNumeric = 'fa-1',
  WidgetLineGraph = 'fa-chart-line',
  WidgetBarGraph = 'fa-chart-simple',
  WidgetPieChart = 'fa-chart-pie',
  WidgetText = 'fa-font',
  WidgetGauge = 'fa-gauge-simple',
  WidgetTable = 'fa-table',
  //Action
  Cancel = 'fa-xmark',
  Success = 'fa-check',
  Property = 'fa-ellipsis-vertical',
  Edit = 'fa-edit',
  Delete = 'fa-trash',
  AddCircle = 'fa-circle-plus',
  Add = 'fa-plus',
  Sub = 'fa-circle-minus',
  UnLock = 'fa-unlock',
  Lock = 'fa-lock',
  LogOut = 'fa-sign-out',
  Close = 'fa-rectangle-xmark',
  Next = 'fa-arrow-right',
  Play = 'fa-play',
  Tenant = 'fa-chess-rook',
  Resize = 'fa-caret-down',
  Copy = 'fa-copy',
  Show = 'fa-eye',

  //
  Warning = 'fa-triangle-exclamation',
  Info = 'fa-info',
  Death = 'fa-skull',
  Mail = 'fa-envelope',
  Light = 'fa-sun',
  Dark = 'fa-moon',

  //Menu
  MenuOpen = 'fa-chevron-down',
  MenuClose = 'fa-chevron-up',
  MenuRight = 'fa-chevron-right',
  MenuLeft = 'fa-chevron-left',
  Asset = 'fa-building',
  Measure = 'fa-ruler',
  Device = 'fa-mobile-screen',
  Admin = 'fa-gear',
  Home = 'fa-home',
  Dashboard = 'fa-chart-line',
  Expand = 'fa-expand',
  Notification = 'fa-bell',
  Alert = 'fa-triangle-exclamation',
  Action = 'fa-person-running',
  Profile = 'fa-user-circle',
  Process = 'fa-diagram-predecessor',
  WalkThrough = 'fa-shoe-prints',
  Burger = 'fa-bars',
  Report = 'fa-file-lines',

  //Face
  Smile = 'fa-face-smile',
  Meh = 'fa-face-meh',
  Sad = 'fa-face-frown',
}
