export enum EIcon {
  User = 'fa-user',
  MagnifyGlass = 'fa-magnifying-glass',
  ConfirmationSucess = 'fa-circle-check',
  ConfirmationCancel = 'fa-circle-xmark',
  ConfirmationWarning = 'fa-circle-exclamation',
  ConfirmationInfo = 'fa-circle-info',
  //Widgets
  WidgetBool = 'fa-toggle-off',
  WidgetNumeric = 'fa-1',
  WidgetLineGraph = 'fa-chart-line',
  WidgetBarGraph = 'fa-chart-simple',
  WidgetPieChart = 'fa-chart-pie',
  WidgetText = 'fa-font',
  WidgetGauge = 'fa-gauge-simple',
  WidgetTable = 'fa-table',
  //Action
  Cancel = 'fa-xmark',
  Success = 'fa-check',
  Property = 'fa-ellipsis-vertical',
  Edit = 'fa-edit',
  Delete = 'fa-trash',
  Add = 'fa-circle-plus',
  UnLock = 'fa-unlock',
  Lock = 'fa-lock',
  LogOut='fa-sign-out',

  //
  Warning = 'fa-triangle-exclamation',
  Info = 'fa-info',
  Death = 'fa-skull',
  //Menu
  MenuOpen = 'fa-chevron-down',
  MenuClose = 'fa-chevron-up',
  MenuRight = 'fa-chevron-right',
  MenuLeft = 'fa-chevron-left',
  Asset = 'fa-building',
  Measure = 'fa-ruler',
  Device = 'fa-mobile-screen',
  Admin = 'fa-gear',
  Home = 'fa-home',
  Dashboard = 'fa-chart-line',
  Expand = 'fa-expand',
  Notification = 'fa-bell',
  Alert = 'fa-exclamation',
  Profile = 'fa-user-circle',
  Process = 'fa-diagram-predecessor',
}
