import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faCheckCircle,
  faSmile,
} from '@fortawesome/free-regular-svg-icons' // regular icon
import {
  faBell,
  faBuilding,
  faChartLine,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircleCheck,
  faCircleExclamation,
  faCircleInfo,
  faCirclePlus,
  faCircleXmark,
  faDiagramPredecessor,
  faEdit,
  faEllipsisVertical,
  faExclamation,
  faExpand,
  faGear,
  faHome,
  faInfo,
  faMagnifyingGlass,
  faMobileScreen,
  faRuler,
  faSkull,
  faTrash,
  faTriangleExclamation,
  faUser,
  faUserCircle,
  faXmark,
} from '@fortawesome/free-solid-svg-icons'

library.add(
  faSmile,
  faUser,
  faCheck,
  faCheckCircle,
  faXmark,
  faTriangleExclamation,
  faInfo,
  faSkull,
  faEllipsisVertical,
  faEdit,
  faTrash,
  faMagnifyingGlass,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChevronDown,
  faBuilding,
  faRuler,
  faMobileScreen,
  faGear,
  faHome,
  faChartLine,
  faExpand,
  faBell,
  faExclamation,
  faUserCircle,
  faDiagramPredecessor,
  faCircleCheck,
  faCircleXmark,
  faCircleExclamation,
  faCircleInfo,
  faCirclePlus
)
//check,x dont work
